services:
  backend:
    build: ./apps/backend/
    ports:
      - "8080:8080"
    environment:
      - PROBLUM_CONFIG_FILE=/app/config.yml
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: "postgres:18-alpine"
    environment:
      - POSTGRES_DB=problum
      - POSTGRES_USER=problum
      - POSTGRES_PASSWORD=problum
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./apps/backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U problum" ]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgres_volume:
