services:
  backend:
    build: ./apps/backend/
    ports:
      - "8080:8080"
    environment:
      - PROBLUM_CONFIG_FILE=/app/config.yml
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  postgres:
    image: "postgres:18-alpine"
    environment:
      - POSTGRES_DB=problum
      - POSTGRES_USER=problum
      - POSTGRES_PASSWORD=problum
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./apps/backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U problum" ]
      interval: 3s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:8.2.2-alpine"
    environment:
      - name=value
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 5s
      retries: 5
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_volume:/data

volumes:
  postgres_volume:
  redis_volume:
