server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 10s

db:
  host: "postgres"
  port: 5432
  user: "problum"
  password: "problum"
  db_name: "problum"
  ssl_mode: "disable"
  max_open_conns: 200
  max_idle_conns: 20
  conn_max_lifetime: 300s
